train_data_dir: "<path to dataset dir>/training.csv"
validation_data_dir: "<path to dataset dir>/validation.csv"
test_data_dir: "<path to dataset dir>/testing.csv"

batch_size: 128
learning_rate: 0.001
num_epochs: 50

data_loader: "ImageLoader"
color_mode: "L"  # L = bw or RGB
input_shape: [129, 500, 1]

model: "topcoder_crnn_finetune" # _finetune"

segment_length: 10  # number of seconds each spectogram represents
pixel_per_second: 50

label_names: ["EN", "DE", "FR", "ES"]
num_classes: 4

# label_names: ["EN", "DE", "FR", "ES", "CN", "RUS"]
# num_classes: 6




